### ISSUE TITLE
Readme.MD


### ISSUE THREAD

**Issue by Savagemikey92** [hmkcode/Android#71]
sun.jvm.hotspot.jdi.SACoreAttachingConnector sun.jvm.hotspot.jdi.SAPIDAttachingConnector sun.jvm.hotspot.jdi.SADebugServerAttachingConnectorhttp://java.sun.com/j2se/1.5.0/docs/guide/jpda/jdwp-spec.htmlemulator.exe/Xverbose

**Comment by HajarePratik** [comment]
Please Stop This Emails. I Can't Want Any Android Details Okey.

Thank You...!!!
